spring.application.name=Backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/myappdb
spring.datasource.username=ashu
spring.datasource.password=a0gt381d@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
# Defer datasource initialization to ensure schema.sql runs after Hibernate
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Schema initialization configuration
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

# Jackson Date Format Configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss

# Server context path Configuaration 
server.servlet.context-path=/

# Multipart File Upload Configuration (50MB max file size)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# Logging Configuration
logging.level.root=INFO
logging.level.com.example=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

app.google-cloud.project-id=tender-487906 

app.google-cloud.processor-id=82a9f90ef4a0f0a

app.google-cloud.credentials-path=/home/asharam-saini/Downloads/document-ai-credentials.json


jwt.secret=3mKp9ZxQvT2Lw8YdHf6BqR1NcUeJ5GsA0rVtX4PnLk7WcS9DjE2FaHbY6QpZtMnK
jwt.expiration=86400000

server.address=0.0.0.0